{% set name = "Orange3-Explain" %}
{% set version = "0.6.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2ee6455e49d9e5ecc22338a9e2ad7dda61a0cc67bef18eddbbb53dc37590e65b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - AnyQt
    - numba >=0.58
    - numpy
    - Orange3 >=3.36.2
    - orange-canvas-core >=0.1.30
    - orange-widget-base >=4.22.0
    - pyqtgraph
    - scipy
    - shap ==0.42.1
    - scikit-learn >=1.3.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - orangecontrib.explain

about:
  home: https://github.com/biolab/orange3-explain
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: Explainable AI add-on for Orange3
  description: |
    Orange3 Explain is an add-on for the Orange3 data mining suite. 
    It provides extensions for explanatory AI.
  doc_url: http://orange3-explain.readthedocs.io/
  dev_url: https://github.com/biolab/orange3-explain

extra:
  recipe-maintainers:
    - PrimozGodec
    - VesnaT
